### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by iProgYou** [Brenda-J/YoungCloud#1]
- [ ] Should have 7 MVPs.
    - [ ] 3 of those are User Auth, Heroku, and Production README.
    - [ ] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [ ] Contains a description sentence of the app
- [ ] Includes two to three detailed bullets on functionality and presentation of feature
- [ ] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each MVP
- [ ] Correctly formatted
    - [ ] MVPs are listed in an ordered list
    - [ ] Each MVP is broken down into bullet points
## Comments

**Comment by iProgYou** [comment]
You will want to simplify the song upload form. Looks good!

**Comment by Brenda-J** [comment]
Did you mean the Song CRUD? Do you recommend only focusing on being able to upload/delete a song as a logged in user? Also I added durations to the mvps.
    On Tuesday, May 25, 2021, 08:15:19 PM EDT, Zack Barbieri ***@***.***> wrote:  
 
 


You will want to simplify the song upload form. Looks good!
